language: node_js
node_js:
  - "node"

git:
  depth: 3

branches:
  only:
  - master

cache:
  directories:
  - $HOME/.yarn-cache

before_install:
  - set -e
  - ./scripts/clean.sh

install:
  #- npm i -g yarn
  #- yarn
  - source ./scripts/installAndroidSDK.sh

script:
  #- npm run test
  - cd android && ./gradlew clean testDebugUnitTest

after_script:
  - echo "BUILD FINISHED"
