language: node_js
node_js:
  - "node"

git:
  depth: 3

branches:
  only:
  - master

cache:
  directories:
  - $HOME/.yarn-cache

install:
  - npm i -g yarn
  - yarn

script:
  - npm run build
  - npm run test
  - npm run release
