language: node_js
node_js:
  - "node"

git:
  depth: 3

branches:
  only:
  - master

cache:
  directories:
  - $HOME/.yarn-cache

before_install:
  - set -e
  # clean
  - watchman watch-del-all 2> /dev/null || true
  - rm -rf "$TMPDIR/react-packager-*" || true

install:
  #- npm i -g yarn
  #- yarn
  # download android sdk
  - curl --location https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz | tar -x -z -C $HOME
  - export ANDROID_HOME=$HOME/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
  - ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk --no-ui -a --filter tools,platform-tools,build-tools-25.0.0,android-23,addon-google_apis-google-24,extra-android-m2repository,extra-google-google_play_services,extra-google-m2repository

script:
  - npm run test

after_script:
  - echo "BUILD FINISHED"
