language: node_js
node_js:
  - "node"

git:
  depth: 3

branches:
  only:
  - master

cache:
  directories:
  - $HOME/.yarn-cache

before_install:
  - set -e
  - ./scripts/clean.sh

install:
  #- npm i -g yarn
  #- yarn
  - ./scripts/installAndroidSDK.sh
  - export ANDROID_HOME=$HOME/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

script:
  #- npm run test
  - cd android && ./gradlew clean testDebugUnitTest

after_script:
  - echo "BUILD FINISHED"
