language: node_js
node_js:
  - "node"

git:
  depth: 3

branches:
  only:
  - master

cache:
  directories:
  - $HOME/.yarn-cache

before_install:
  - set -e
  # clean
  - watchman watch-del-all 2> /dev/null || true
  - rm -rf "$TMPDIR/react-packager-*" || true


install:
  - npm i -g yarn
  - yarn

script:
  - npm run test

after_script:
  - echo "BUILD FINISHED"
