language: node_js
node_js:
  - "node"

git:
  depth: 3

branches:
  only:
  - master

cache:
  directories:
  - $HOME/.yarn-cache

before_install:
  - set -e
  - scripts/clean

install:
  #- npm i -g yarn
  #- yarn
  - scripts/installAndroidSDK

script:
  - npm run test

after_script:
  - echo "BUILD FINISHED"
